### ISSUE TITLE
/usr/local/bin/git: no such file or directory

### ISSUE THREAD

**Issue by skibitsky** [nikitavoloboev/gitupdate#2]
### Bug 🐞
I receive `fork/exec /usr/local/bin/git: no such file or directory` every time when I run it with the path argument. 

I suppose it happens because the path to git executable is hardcoded like here: https://github.com/nikitavoloboev/gitupdate/blob/master/main.go#L31

It works if I use just `git` instead of `/usr/local/bin/git`

**Comment by nikitavoloboev** [comment]
yeah need to change it to lookup path for `git` command. Feel free to send PR otherwise I look into it in a bit.
